import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Navbar from "../components/Navbar"
import Setting from "../components/Setting"

function MyApp({ Component, pageProps }: AppProps) {
  return (
        <main className='flex'>
          <Navbar />
          <Setting />
          <Head>
            <title>Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>


          <Component {...pageProps} />
        </main>)
}

export default MyApp
